#!/bin/bash
# shellcheck shell=bash
#
# Flavor loader, shared by the host CLI (bin/rcheck) and by the container
# entrypoints. Sourced, never executed.
#
# Deliberately has no dependencies beyond bash, awk and sed: it has to run
# inside a plain debian base image before anything has been installed, and on
# whatever the user's host happens to be.
#
# See flavors/SCHEMA for the meaning of every key.

## Every key in the schema, in schema order. The test suite reads this list, so
## adding a key here and to flavors/SCHEMA is all that is needed to extend the
## format.
RCHECK_FLAVOR_KEYS="
FLAVOR_ID FLAVOR_TITLE CRAN_ISSUE_KIND CRAN_HOST_OS TIER STATUS REFERENCE
BASE_FAMILY BASE_IMAGE BASE_TAG APT_COMPONENTS
R_BUILD_SYSDEPS R_BUILD_METHOD R_CONFIGURE_ARGS
R_CC R_CXX R_FC R_CFLAGS R_CXXFLAGS R_FFLAGS R_LDFLAGS R_MAIN_LDFLAGS
CHECK_RENVIRON CHECK_RUNTIME_ENV CHECK_EXTRA_ARGS
NOTES
"

## Keys that must be non-empty in every flavor file.
RCHECK_FLAVOR_REQUIRED="
FLAVOR_ID FLAVOR_TITLE CRAN_HOST_OS TIER STATUS
BASE_FAMILY BASE_IMAGE BASE_TAG R_BUILD_METHOD
"

rcheck_die() { printf '%s\n' "rcheck: $*" >&2; exit 1; }
rcheck_info() { printf '== %s\n' "$*" >&2; }

## Where to look for flavor files, in order. The first hit wins, so a bind
## mounted working copy shadows the definitions baked into the image and a
## flavor can be edited without a rebuild.
rcheck_flavor_path() {
    printf '%s' "${RCHECK_FLAVOR_PATH:-/rcheck/flavors.local:/rcheck/flavors}"
}

rcheck_flavor_file() {
    local id=$1 dir
    case $id in
        */*|.*|"") return 1 ;;   ## no path traversal, no dotfiles
    esac
    local IFS=:
    for dir in $(rcheck_flavor_path); do
        if [ -f "$dir/$id.conf" ]; then
            printf '%s\n' "$dir/$id.conf"
            return 0
        fi
    done
    return 1
}

rcheck_flavor_list() {
    local dir f id
    local IFS=:
    for dir in $(rcheck_flavor_path); do
        [ -d "$dir" ] || continue
        for f in "$dir"/*.conf; do
            [ -f "$f" ] || continue
            id=${f##*/}; id=${id%.conf}
            printf '%s\n' "$id"
        done
    done | sort -u
}

## Load a flavor into the current shell. Clears every schema key first so that
## loading a second flavor cannot inherit values from the first.
rcheck_flavor_load() {
    local id=$1 file key
    file=$(rcheck_flavor_file "$id") ||
        rcheck_die "unknown flavor '$id' (looked in $(rcheck_flavor_path)); try 'rcheck flavors'"

    for key in $RCHECK_FLAVOR_KEYS; do
        unset "$key"
        eval "$key=''"
    done
    ## Defaults for keys a flavor may legitimately omit.
    APT_COMPONENTS=main
    R_BUILD_METHOD=cran-qa

    # shellcheck disable=SC1090  # path is resolved above and repo-controlled
    . "$file"

    RCHECK_FLAVOR_FILE=$file

    [ "$FLAVOR_ID" = "$id" ] ||
        rcheck_die "$file declares FLAVOR_ID='$FLAVOR_ID' but is named '$id.conf'"

    for key in $RCHECK_FLAVOR_REQUIRED; do
        eval "local v=\${$key}"
        # shellcheck disable=SC2154  # v is assigned by the eval above
        [ -n "$v" ] || rcheck_die "$file: required key $key is empty"
    done

    case $R_BUILD_METHOD in
        cran-qa|configure) ;;
        *) rcheck_die "$file: R_BUILD_METHOD must be cran-qa or configure, got '$R_BUILD_METHOD'" ;;
    esac
    case $BASE_FAMILY in
        debian) ;;
        fedora) rcheck_die "$file: BASE_FAMILY=fedora is declared but not implemented (see docs/architecture.md ADR-0005)" ;;
        *) rcheck_die "$file: BASE_FAMILY must be debian or fedora, got '$BASE_FAMILY'" ;;
    esac
    case $STATUS in
        implemented|experimental|planned) ;;
        *) rcheck_die "$file: STATUS must be implemented, experimental or planned, got '$STATUS'" ;;
    esac
    case $TIER in
        1|2|3) ;;
        *) rcheck_die "$file: TIER must be 1, 2 or 3, got '$TIER'" ;;
    esac
}

## ---------------------------------------------------------------------------
## Build-time application
## ---------------------------------------------------------------------------

## Write a config.site for R's configure and export the same settings into the
## environment. Both, on purpose: autoconf reads CONFIG_SITE, but exporting as
## well means a flavor still mostly works if a build driver re-invokes configure
## without inheriting CONFIG_SITE.
rcheck_flavor_write_config_site() {
    local out=$1
    {
        echo "## Generated by rcheck from ${RCHECK_FLAVOR_FILE}. Do not edit."
        echo "## Flavor: ${FLAVOR_ID} -- ${FLAVOR_TITLE}"
        [ -n "$R_CC" ]           && echo "CC='${R_CC}'"
        [ -n "$R_CXX" ]          && echo "CXX='${R_CXX}'"
        [ -n "$R_FC" ]           && { echo "FC='${R_FC}'"; echo "F77='${R_FC}'"; }
        [ -n "$R_CFLAGS" ]       && echo "CFLAGS='${R_CFLAGS}'"
        [ -n "$R_CXXFLAGS" ]     && echo "CXXFLAGS='${R_CXXFLAGS}'"
        [ -n "$R_FFLAGS" ]       && { echo "FFLAGS='${R_FFLAGS}'"; echo "FCFLAGS='${R_FFLAGS}'"; }
        [ -n "$R_LDFLAGS" ]      && echo "LDFLAGS='${R_LDFLAGS}'"
        [ -n "$R_MAIN_LDFLAGS" ] && echo "MAIN_LDFLAGS='${R_MAIN_LDFLAGS}'"
        :
    } > "$out"
}

rcheck_flavor_export_build_env() {
    [ -n "$R_CC" ]           && export CC="$R_CC"
    [ -n "$R_CXX" ]          && export CXX="$R_CXX"
    [ -n "$R_FC" ]           && { export FC="$R_FC"; export F77="$R_FC"; }
    [ -n "$R_CFLAGS" ]       && export CFLAGS="$R_CFLAGS"
    [ -n "$R_CXXFLAGS" ]     && export CXXFLAGS="$R_CXXFLAGS"
    [ -n "$R_FFLAGS" ]       && { export FFLAGS="$R_FFLAGS"; export FCFLAGS="$R_FFLAGS"; }
    [ -n "$R_LDFLAGS" ]      && export LDFLAGS="$R_LDFLAGS"
    [ -n "$R_MAIN_LDFLAGS" ] && export MAIN_LDFLAGS="$R_MAIN_LDFLAGS"
    :
}

## ---------------------------------------------------------------------------
## Check-time application
## ---------------------------------------------------------------------------

## Append the flavor's settings to a check.Renviron. R CMD check reads this file
## itself (R_CHECK_ENVIRON, default ~/.R/check.Renviron), which is why it is the
## preferred channel: it does not depend on how the surrounding driver script
## invokes the check.
##
## Appends between markers, and removes any block a previous run left behind
## first. Under docker the home directory is fresh every run so this would not
## matter; under apptainer it is a persistent directory, and appending blindly
## would grow the file on every check.
rcheck_flavor_write_check_renviron() {
    local out=$1 tmp
    mkdir -p "$(dirname "$out")"

    if [ -f "$out" ]; then
        tmp=$out.rcheck.tmp
        awk '/^## >>> rcheck flavor/ { skip = 1 }
             !skip { print }
             /^## <<< rcheck flavor/ { skip = 0 }' "$out" > "$tmp" && mv "$tmp" "$out"
    fi

    [ -n "$CHECK_RENVIRON" ] || return 0
    {
        echo "## >>> rcheck flavor ${FLAVOR_ID}"
        printf '%s\n' "$CHECK_RENVIRON" | sed -e 's/^[[:space:]]*//' -e '/^$/d'
        echo "## <<< rcheck flavor"
    } >> "$out"
}

## Export CHECK_RUNTIME_ENV. These are settings for the sanitizer runtimes and
## the BLAS, not for R, so check.Renviron is the wrong channel for them.
rcheck_flavor_export_runtime_env() {
    local line
    [ -n "$CHECK_RUNTIME_ENV" ] || return 0
    while IFS= read -r line; do
        line=${line#"${line%%[![:space:]]*}"}   ## strip leading blanks
        [ -n "$line" ] || continue
        case $line in
            [A-Za-z_]*=*) export "${line?}" ;;
            *) rcheck_die "${RCHECK_FLAVOR_FILE}: CHECK_RUNTIME_ENV line is not VAR=value: $line" ;;
        esac
    done <<EOF
$CHECK_RUNTIME_ENV
EOF
}

## ---------------------------------------------------------------------------
## Reporting
## ---------------------------------------------------------------------------

_rcheck_json_escape() {
    awk 'BEGIN { ORS="" }
         { gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); gsub(/\t/, "\\t"); gsub(/\r/, "\\r")
           if (NR > 1) printf "\\n"
           printf "%s", $0 }'
}

## Emit the loaded flavor as JSON. Used for `rcheck describe --json`, for the
## per-run manifest, and by the test suite.
rcheck_flavor_json() {
    local key first=1
    printf '{\n'
    for key in $RCHECK_FLAVOR_KEYS; do
        eval "local value=\${$key}"
        [ $first -eq 1 ] || printf ',\n'
        first=0
        # shellcheck disable=SC2154  # value is assigned by the eval above
        printf '  "%s": "%s"' "$key" "$(printf '%s' "$value" | _rcheck_json_escape)"
    done
    printf '\n}\n'
}
